00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/cars/urls.py
from django.urls import path 
from . import views

app_name = 'cars'
# domain.com/cars/delete
urlpatterns = [
    path('list/',views.list,name='list'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),
]

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/my_car_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/',include('cars.urls'))
]

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/cars/views.py
from django.shortcuts import render


# Create your views here.
def list(request):
    return render(request,'cars/list.html')

def add(request):
    return render(request,'cars/add.html')

def delete(request):
    return render(request,'cars/delete.html')

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content%}
<h1>ADD.html</h1>
{% endblock%}

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content%}
<h1>DELETE.HTML</h1>
{% endblock%}

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content%}

<h1>LIST.HTML</h1>
{% endblock%}

00-Resources/DJANGO_COURSE_V2/09-Django-Admin-Portal/my_car_site_v01/templates/base.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <title>Document</title>
</head>
<body>

  <!-- NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid"> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav"> 
          <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
          <a class="nav-link" href="{% url 'cars:add' %}">ADD</a> 
          <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a> 
        </div>
      </div>
    </div>
  </nav>
{%block content%}
{% endblock %}  
</body>
</html>